#!/usr/bin/env python3
"""
Ribit 2.0 - Unified Credentials Setup
======================================

Interactive script to configure Matrix and DeltaChat credentials for Ribit 2.0.
Creates or updates the .env file with all necessary authentication details.

Usage:
    python3 setup_credentials.py
    or
    ./setup_credentials.py
"""

import os
import sys
from pathlib import Path
from getpass import getpass

# ANSI color codes
GREEN = '\033[92m'
YELLOW = '\033[93m'
CYAN = '\033[96m'
MAGENTA = '\033[95m'
BOLD = '\033[1m'
RESET = '\033[0m'


def print_banner():
    """Print ASCII art banner"""
    banner = f"""
{CYAN}╔═══════════════════════════════════════════════════════════════════╗
║                                                                   ║
║  ██████╗ ██╗██████╗ ██╗████████╗    ██████╗     ██████╗          ║
║  ██╔══██╗██║██╔══██╗██║╚══██╔══╝    ╚════██╗   ██╔═████╗         ║
║  ██████╔╝██║██████╔╝██║   ██║        █████╔╝   ██║██╔██║         ║
║  ██╔══██╗██║██╔══██╗██║   ██║       ██╔═══╝    ████╔╝██║         ║
║  ██║  ██║██║██████╔╝██║   ██║       ███████╗██╗╚██████╔╝         ║
║  ╚═╝  ╚═╝╚═╝╚═════╝ ╚═╝   ╚═╝       ╚══════╝╚═╝ ╚═════╝          ║
║                                                                   ║
║            {MAGENTA}Credentials Setup Wizard{CYAN}                             ║
║                                                                   ║
╚═══════════════════════════════════════════════════════════════════╝{RESET}
"""
    print(banner)


def load_existing_env():
    """Load existing .env file if it exists"""
    env_path = Path('.env')
    env_vars = {}
    
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    
    return env_vars


def save_env_file(env_vars):
    """Save environment variables to .env file"""
    env_path = Path('.env')
    
    with open(env_path, 'w') as f:
        f.write("# Ribit 2.0 Credentials Configuration\n")
        f.write("# Generated by setup_credentials.py\n")
        f.write("#\n")
        f.write("# IMPORTANT: Keep this file secure and never commit it to version control!\n")
        f.write("#\n\n")
        
        # Matrix credentials
        f.write("# ========================================\n")
        f.write("# Matrix Credentials\n")
        f.write("# ========================================\n")
        if 'MATRIX_HOMESERVER' in env_vars:
            f.write(f"MATRIX_HOMESERVER={env_vars['MATRIX_HOMESERVER']}\n")
        if 'MATRIX_USER_ID' in env_vars:
            f.write(f"MATRIX_USER_ID={env_vars['MATRIX_USER_ID']}\n")
        if 'MATRIX_PASSWORD' in env_vars:
            f.write(f"MATRIX_PASSWORD={env_vars['MATRIX_PASSWORD']}\n")
        if 'MATRIX_ACCESS_TOKEN' in env_vars:
            f.write(f"MATRIX_ACCESS_TOKEN={env_vars['MATRIX_ACCESS_TOKEN']}\n")
        if 'MATRIX_DEVICE_ID' in env_vars:
            f.write(f"MATRIX_DEVICE_ID={env_vars['MATRIX_DEVICE_ID']}\n")
        f.write("\n")
        
        # DeltaChat credentials
        f.write("# ========================================\n")
        f.write("# DeltaChat Credentials\n")
        f.write("# ========================================\n")
        if 'DELTACHAT_EMAIL' in env_vars:
            f.write(f"DELTACHAT_EMAIL={env_vars['DELTACHAT_EMAIL']}\n")
        if 'DELTACHAT_PASSWORD' in env_vars:
            f.write(f"DELTACHAT_PASSWORD={env_vars['DELTACHAT_PASSWORD']}\n")
        if 'DELTACHAT_IMAP' in env_vars:
            f.write(f"DELTACHAT_IMAP={env_vars['DELTACHAT_IMAP']}\n")
        if 'DELTACHAT_SMTP' in env_vars:
            f.write(f"DELTACHAT_SMTP={env_vars['DELTACHAT_SMTP']}\n")
        if 'DELTACHAT_IMAP_SECURITY' in env_vars:
            f.write(f"DELTACHAT_IMAP_SECURITY={env_vars['DELTACHAT_IMAP_SECURITY']}\n")
        if 'DELTACHAT_SMTP_SECURITY' in env_vars:
            f.write(f"DELTACHAT_SMTP_SECURITY={env_vars['DELTACHAT_SMTP_SECURITY']}\n")
    
    # Set secure permissions
    os.chmod(env_path, 0o600)
    print(f"\n{GREEN}✅ Credentials saved to .env file{RESET}")
    print(f"{YELLOW}⚠️  File permissions set to 600 (owner read/write only){RESET}\n")


def setup_matrix_credentials(existing_env):
    """Interactive setup for Matrix credentials"""
    print(f"\n{BOLD}{CYAN}{'='*70}{RESET}")
    print(f"{BOLD}{CYAN}Matrix Credentials Setup{RESET}")
    print(f"{BOLD}{CYAN}{'='*70}{RESET}\n")
    
    print(f"{YELLOW}Matrix is a decentralized messaging protocol.{RESET}")
    print(f"{YELLOW}You'll need an account on a Matrix homeserver.{RESET}\n")
    
    # Ask if user wants to configure Matrix
    configure = input(f"{BOLD}Configure Matrix credentials? (y/n) [{CYAN}y{RESET}]: ").strip().lower()
    if configure and configure != 'y':
        print(f"{YELLOW}Skipping Matrix configuration...{RESET}")
        return existing_env
    
    env_vars = existing_env.copy()
    
    # Homeserver
    default_homeserver = env_vars.get('MATRIX_HOMESERVER', 'https://matrix.envs.net')
    homeserver = input(f"{BOLD}Matrix Homeserver [{CYAN}{default_homeserver}{RESET}]: ").strip()
    env_vars['MATRIX_HOMESERVER'] = homeserver if homeserver else default_homeserver
    
    # User ID
    default_user = env_vars.get('MATRIX_USER_ID', '')
    user_id = input(f"{BOLD}Matrix User ID (e.g., @username:envs.net) [{CYAN}{default_user}{RESET}]: ").strip()
    env_vars['MATRIX_USER_ID'] = user_id if user_id else default_user
    
    # Authentication method choice
    print(f"\n{YELLOW}Matrix Authentication Method:{RESET}")
    print(f"  1. Password (username + password)")
    print(f"  2. Access Token (more secure, recommended)\n")
    
    auth_method = input(f"{BOLD}Choose authentication method (1/2) [{CYAN}2{RESET}]: ").strip()
    
    if auth_method == '1':
        # Password authentication
        has_password = env_vars.get('MATRIX_PASSWORD', '')
        if has_password:
            update_password = input(f"{BOLD}Update existing Matrix password? (y/n) [{CYAN}n{RESET}]: ").strip().lower()
            if update_password == 'y':
                password = getpass(f"{BOLD}Matrix Password (hidden): {RESET}")
                if password:
                    env_vars['MATRIX_PASSWORD'] = password
                    # Remove access token if switching to password
                    env_vars.pop('MATRIX_ACCESS_TOKEN', None)
        else:
            password = getpass(f"{BOLD}Matrix Password (hidden): {RESET}")
            if password:
                env_vars['MATRIX_PASSWORD'] = password
                # Remove access token if switching to password
                env_vars.pop('MATRIX_ACCESS_TOKEN', None)
    else:
        # Access Token authentication (default)
        print(f"\n{YELLOW}How to get your Matrix access token:{RESET}")
        print(f"  1. Go to https://app.element.io")
        print(f"  2. Log in with your Matrix account")
        print(f"  3. Click your profile (top left) → Settings")
        print(f"  4. Go to 'Help & About' → Scroll to 'Access Token'")
        print(f"  5. Click to reveal and copy the token\n")
        
        has_token = env_vars.get('MATRIX_ACCESS_TOKEN', '')
        if has_token:
            update_token = input(f"{BOLD}Update existing access token? (y/n) [{CYAN}n{RESET}]: ").strip().lower()
            if update_token == 'y':
                access_token = getpass(f"{BOLD}Matrix Access Token (hidden): {RESET}")
                if access_token:
                    env_vars['MATRIX_ACCESS_TOKEN'] = access_token
                    # Remove password if switching to token
                    env_vars.pop('MATRIX_PASSWORD', None)
        else:
            access_token = getpass(f"{BOLD}Matrix Access Token (hidden): {RESET}")
            if access_token:
                env_vars['MATRIX_ACCESS_TOKEN'] = access_token
                # Remove password if switching to token
                env_vars.pop('MATRIX_PASSWORD', None)
    
    # Device ID (optional)
    default_device = env_vars.get('MATRIX_DEVICE_ID', '')
    device_id = input(f"{BOLD}Matrix Device ID (optional) [{CYAN}{default_device or 'auto-generate'}{RESET}]: ").strip()
    if device_id:
        env_vars['MATRIX_DEVICE_ID'] = device_id
    
    return env_vars


def setup_deltachat_credentials(existing_env):
    """Interactive setup for DeltaChat credentials"""
    print(f"\n{BOLD}{CYAN}{'='*70}{RESET}")
    print(f"{BOLD}{CYAN}DeltaChat Credentials Setup{RESET}")
    print(f"{BOLD}{CYAN}{'='*70}{RESET}\n")
    
    print(f"{YELLOW}DeltaChat uses standard email protocols (IMAP/SMTP).{RESET}")
    print(f"{YELLOW}You'll need an email account with IMAP/SMTP access.{RESET}\n")
    
    # Ask if user wants to configure DeltaChat
    configure = input(f"{BOLD}Configure DeltaChat credentials? (y/n) [{CYAN}y{RESET}]: ").strip().lower()
    if configure and configure != 'y':
        print(f"{YELLOW}Skipping DeltaChat configuration...{RESET}")
        return existing_env
    
    env_vars = existing_env.copy()
    
    # Email
    default_email = env_vars.get('DELTACHAT_EMAIL', '')
    email = input(f"{BOLD}DeltaChat Email Address [{CYAN}{default_email}{RESET}]: ").strip()
    env_vars['DELTACHAT_EMAIL'] = email if email else default_email
    
    # Password
    has_password = env_vars.get('DELTACHAT_PASSWORD', '')
    if has_password:
        update_password = input(f"{BOLD}Update existing email password? (y/n) [{CYAN}n{RESET}]: ").strip().lower()
        if update_password == 'y':
            password = getpass(f"{BOLD}Email Password (hidden): {RESET}")
            if password:
                env_vars['DELTACHAT_PASSWORD'] = password
    else:
        password = getpass(f"{BOLD}Email Password (hidden): {RESET}")
        if password:
            env_vars['DELTACHAT_PASSWORD'] = password
    
    # IMAP Server
    print(f"\n{YELLOW}Common IMAP servers:{RESET}")
    print(f"  Gmail:     imap.gmail.com")
    print(f"  Outlook:   outlook.office365.com")
    print(f"  Yahoo:     imap.mail.yahoo.com")
    print(f"  ProtonMail: 127.0.0.1 (requires ProtonMail Bridge)\n")
    
    default_imap = env_vars.get('DELTACHAT_IMAP', '')
    imap_server = input(f"{BOLD}IMAP Server (e.g., imap.gmail.com) [{CYAN}{default_imap}{RESET}]: ").strip()
    env_vars['DELTACHAT_IMAP'] = imap_server if imap_server else default_imap
    
    # SMTP Server
    print(f"\n{YELLOW}Common SMTP servers:{RESET}")
    print(f"  Gmail:     smtp.gmail.com")
    print(f"  Outlook:   smtp.office365.com")
    print(f"  Yahoo:     smtp.mail.yahoo.com")
    print(f"  ProtonMail: 127.0.0.1 (requires ProtonMail Bridge)\n")
    
    default_smtp = env_vars.get('DELTACHAT_SMTP', '')
    smtp_server = input(f"{BOLD}SMTP Server (e.g., smtp.gmail.com) [{CYAN}{default_smtp}{RESET}]: ").strip()
    env_vars['DELTACHAT_SMTP'] = smtp_server if smtp_server else default_smtp
    
    # Security settings
    print(f"\n{YELLOW}Security Settings:{RESET}")
    
    default_imap_security = env_vars.get('DELTACHAT_IMAP_SECURITY', 'SSL/TLS')
    imap_security = input(f"{BOLD}IMAP Security (SSL/TLS or STARTTLS) [{CYAN}{default_imap_security}{RESET}]: ").strip()
    env_vars['DELTACHAT_IMAP_SECURITY'] = imap_security if imap_security else default_imap_security
    
    default_smtp_security = env_vars.get('DELTACHAT_SMTP_SECURITY', 'STARTTLS')
    smtp_security = input(f"{BOLD}SMTP Security (STARTTLS or SSL/TLS) [{CYAN}{default_smtp_security}{RESET}]: ").strip()
    env_vars['DELTACHAT_SMTP_SECURITY'] = smtp_security if smtp_security else default_smtp_security
    
    return env_vars


def main():
    """Main function"""
    print_banner()
    
    print(f"{BOLD}Welcome to the Ribit 2.0 Credentials Setup Wizard!{RESET}\n")
    print(f"This wizard will help you configure credentials for:")
    print(f"  • {CYAN}Matrix{RESET} - Decentralized messaging protocol")
    print(f"  • {MAGENTA}DeltaChat{RESET} - Email-based messaging\n")
    
    # Load existing credentials
    existing_env = load_existing_env()
    if existing_env:
        print(f"{GREEN}✓ Found existing .env file with {len(existing_env)} variables{RESET}")
        print(f"{YELLOW}  You can update existing values or keep them as defaults{RESET}\n")
    
    # Setup Matrix credentials
    env_vars = setup_matrix_credentials(existing_env)
    
    # Setup DeltaChat credentials
    env_vars = setup_deltachat_credentials(env_vars)
    
    # Save to .env file
    print(f"\n{BOLD}{CYAN}{'='*70}{RESET}")
    print(f"{BOLD}{CYAN}Summary{RESET}")
    print(f"{BOLD}{CYAN}{'='*70}{RESET}\n")
    
    print(f"{BOLD}Configured credentials:{RESET}")
    
    # Matrix summary
    if 'MATRIX_USER_ID' in env_vars and env_vars['MATRIX_USER_ID']:
        print(f"\n{CYAN}Matrix:{RESET}")
        print(f"  Homeserver: {env_vars.get('MATRIX_HOMESERVER', 'Not set')}")
        print(f"  User ID:    {env_vars.get('MATRIX_USER_ID', 'Not set')}")
        if env_vars.get('MATRIX_PASSWORD'):
            print(f"  Password:   {'*' * 12} (set)")
        elif env_vars.get('MATRIX_ACCESS_TOKEN'):
            print(f"  Token:      {'***' + env_vars['MATRIX_ACCESS_TOKEN'][-10:]}")
        else:
            print(f"  Auth:       Not set")
    
    # DeltaChat summary
    if 'DELTACHAT_EMAIL' in env_vars and env_vars['DELTACHAT_EMAIL']:
        print(f"\n{MAGENTA}DeltaChat:{RESET}")
        print(f"  Email:      {env_vars.get('DELTACHAT_EMAIL', 'Not set')}")
        print(f"  IMAP:       {env_vars.get('DELTACHAT_IMAP', 'Not set')} ({env_vars.get('DELTACHAT_IMAP_SECURITY', 'Not set')})")
        print(f"  SMTP:       {env_vars.get('DELTACHAT_SMTP', 'Not set')} ({env_vars.get('DELTACHAT_SMTP_SECURITY', 'Not set')})")
    
    # Confirm save
    print(f"\n{BOLD}Save these credentials to .env file?{RESET}")
    confirm = input(f"(y/n) [{CYAN}y{RESET}]: ").strip().lower()
    
    if confirm and confirm != 'y':
        print(f"\n{YELLOW}Setup cancelled. No changes made.{RESET}")
        return 1
    
    save_env_file(env_vars)
    
    print(f"{BOLD}{GREEN}{'='*70}{RESET}")
    print(f"{BOLD}{GREEN}✅ Setup Complete!{RESET}")
    print(f"{BOLD}{GREEN}{'='*70}{RESET}\n")
    
    print(f"Your credentials are now saved in {BOLD}.env{RESET}")
    print(f"\n{YELLOW}Next steps:{RESET}")
    print(f"  1. Run the bot: {CYAN}./run_bot.sh{RESET}")
    print(f"  2. Or run directly: {CYAN}python3 -m ribit_2_0.matrix_bot{RESET}")
    print(f"\n{YELLOW}⚠️  Security reminder:{RESET}")
    print(f"  • Never commit .env to version control")
    print(f"  • Keep your access tokens secure")
    print(f"  • Regenerate tokens if compromised\n")
    
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print(f"\n\n{YELLOW}Setup cancelled by user.{RESET}")
        sys.exit(1)
    except Exception as e:
        print(f"\n{BOLD}❌ Error: {e}{RESET}")
        sys.exit(1)
